---
name: main
on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Check gh auth status
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GTOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GTOKEN }}

      - name: Build and Push to Registries
        uses: docker/build-push-action@v6
        with:
          tags: |
            ghcr.io/${{ github.repository }}:latest

      - name: Push only latest tag on main branch
        uses: docker/build-push-action@v6
        with:
          tags: |
            ghcr.io/${{ github.repository }}:latest

#      - name: Make the package public
#        run: |
#          gh api --method PATCH \
#            -H "Accept: application/vnd.github+json" \
#            /org/rakus-dev/packages/container/${PACKAGE_NAME}/visibility \
#            -f visibility=public
#        env:
#          GH_TOKEN: ${{ secrets.GTOKEN }}
#          PACKAGE_NAME: actions_test
  
